// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace UFOT
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Cuenta
    {
        [JsonProperty("idCliente")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long IdCliente { get; set; }

        [JsonProperty("idCuenta")]
        public long IdCuenta { get; set; }

        [JsonProperty("tipoCuenta")]
        public string TipoCuenta { get; set; }

        [JsonProperty("moneda")]
        public string Moneda { get; set; }

        [JsonProperty("estadoCuenta")]
        public string EstadoCuenta { get; set; }

        [JsonProperty("balance")]
        public double Balance { get; set; }

        [JsonProperty("fechaApertura")]
        public DateTimeOffset FechaApertura { get; set; }

        [JsonProperty("fechaCierre")]
        public DateTimeOffset FechaCierre { get; set; }
    }

    public partial class Cuenta
    {
        public static List<Cuenta> FromJson(string json) => JsonConvert.DeserializeObject<List<Cuenta>>(json, UFOT.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Cuenta> self) => JsonConvert.SerializeObject(self, UFOT.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
