// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var prestamo = Prestamo.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Prestamo
    {
        [JsonProperty("idPrestamo")]
        public long IdPrestamo { get; set; }

        [JsonProperty("idCliente")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long IdCliente { get; set; }

        [JsonProperty("monto")]
        public long Monto { get; set; }

        [JsonProperty("fechaSolicitud")]
        public DateTimeOffset FechaSolicitud { get; set; }

        [JsonProperty("fechaDesembolso")]
        public DateTimeOffset FechaDesembolso { get; set; }

        [JsonProperty("tasaInteres")]
        public long TasaInteres { get; set; }

        [JsonProperty("tipoPrestamo")]
        public string TipoPrestamo { get; set; }

        [JsonProperty("estadoPrestamo")]
        public string EstadoPrestamo { get; set; }

        [JsonProperty("cuotaMensual")]
        public double CuotaMensual { get; set; }

        [JsonProperty("fechaPagoUlltimaCuota")]
        public object FechaPagoUlltimaCuota { get; set; }

        [JsonProperty("garantia")]
        public string Garantia { get; set; }

        [JsonProperty("estado")]
        public string Estado { get; set; }
    }

    public partial class Prestamo
    {
        public static List<Prestamo> FromJson(string json) => JsonConvert.DeserializeObject<List<Prestamo>>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Prestamo> self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
